{
  "openapi": "3.0.0",
  "info": {
    "version": "0.2",
    "title": "pgCOVAPI",
    "description": "API che fornisce dati riguardo l'epidemia COVID in Italia. <br> Progetto maturità 2021 5^C Informatica IIS A.Avogadro. <br> <b>Alunni:</b> Silvio Caprara, Pietro Chiartano, Yun Qing Zhou.",
    "termsOfService": "",
    "contact": {
      "name": "",
      "url": ""
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "servers": [
    {
      "url": "https://pgcovapi.herokuapp.com/api/"
    }
  ],
  "tags": [
    {
      "name": "Regioni",
      "description": "Dati COVID delle singole regioni"
    },
    {
      "name": "Nazione",
      "description": "Dati COVID per l'andamento dell'intera nazione"
    }
  ],
  "paths": {
    "/regioni/": {
      "get": {
        "tags": [
          "Regioni"
        ],
        "description": "Ritorna i dati riguardanti l'epidemia in tutte le regioni.",
        "operationId": "RegionifindRegione",
        "parameters": [
          {
            "name": "campo",
            "in": "query",
            "description": "Campo specifico da ritornare. I campi <b>data</b>, <b>stato</b>, <b>codice_regione</b> e <b>denominazione_regione</b> sono ritornati in ogni caso.",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "ricoverati_con_sintomi",
                  "terapia_intensiva",
                  "totale_ospedalizzati",
                  "isolamento_domiciliare",
                  "totale_positivi",
                  "variazione_totale_positivi",
                  "nuovi_positivi",
                  "dimessi_guariti",
                  "deceduti",
                  "totale_casi",
                  "tamponi",
                  "casi_testati",
                  "ingressi_terapia_intensiva",
                  "totale_positivi_test_molecolare",
                  "totale_positivi_test_antigenico_rapido",
                  "tamponi_test_molecolare",
                  "tamponi_test_antigenico_rapido"
                ]
              }
            }
          },
          {
            "name": "mese",
            "in": "query",
            "description": "Mese da ricercare. Va riportato in formato <b>yyyy-mm</b>, ad esempio 2020-09 per ottenere i dati del mese di settembre 2020.<br> Questo parametro è incompatibile con `giorni`, `dataInizio`, `dataFine`",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "giorni",
            "in": "query",
            "description": "In base al valore N inserito, ritorna i record degli ultimi N giorni. Ad esempio, se il valore inserito è 30 ritorna i record degli ultimi 30 giorni. <br> Questo parametro è incompatibile con `mese`, `dataInizio`, `dataFine`.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "dataInizio",
            "in": "query",
            "description": "Data in formato <b>yyyy-mm-gg</b>. Vengono ritornati tutti i documenti con le date maggiori e uguali alla data specificata.<br> Questo parametro è incompatibile con `giorni`, `mese`.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "dataFine",
            "in": "query",
            "description": "Data in formato <b>yyyy-mm-gg</b>. Vengono ritornati tutti i documenti con le date minori e uguali alla data specificata.<br> Questo parametro è incompatibile con `giorni`, `mese`.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "summary": "Ritorna i dati riguardanti l'epidemia in tutte le regioni.",
        "responses": {
          "200": {
            "description": "Risposta con un array di oggetti, ognuno rappresentante un giorno in una regione",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Regione"
                },
                "example": {
                  "data": "2021-03-27T17:00:00",
                  "stato": "ITA",
                  "codice_regione": 1,
                  "denominazione_regione": "Piemonte",
                  "lat": 45.0732745,
                  "long": 7.680687483,
                  "ricoverati_con_sintomi": 3767,
                  "terapia_intensiva": 360,
                  "totale_ospedalizzati": 4127,
                  "isolamento_domiciliare": 31458,
                  "totale_positivi": 35585,
                  "variazione_totale_positivi": 450,
                  "nuovi_positivi": 2636,
                  "dimessi_guariti": 256309,
                  "deceduti": 10180,
                  "casi_da_sospetto_diagnostico": null,
                  "casi_da_screening": null,
                  "totale_casi": 302074,
                  "tamponi": 3231331,
                  "casi_testati": 1484100,
                  "note": null,
                  "ingressi_terapia_intensiva": 27,
                  "note_test": null,
                  "note_casi": null,
                  "totale_positivi_test_molecolare": 288766,
                  "totale_positivi_test_antigenico_rapido": 13308,
                  "tamponi_test_molecolare": 2350377,
                  "tamponi_test_antigenico_rapido": 880954,
                  "codice_nuts_1": "ITC",
                  "codice_nuts_2": "ITC1"
                }
              }
            }
          }
        }
      }
    },
    "/regioni/{regione}": {
      "get": {
        "tags": [
          "Regioni"
        ],
        "description": "Ritorna i dati riguardanti l'epidemia in una regione specifica.\n",
        "operationId": "RegionifindAllCampo",
        "parameters": [
          {
            "name": "regione",
            "in": "path",
            "description": "Regione italiana da ricercare.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "campo",
            "in": "query",
            "description": "Campo specifico da ritornare. I campi <b>data</b>, <b>stato</b>, <b>codice_regione</b> e <b>denominazione_regione</b> sono ritornati in ogni caso.",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "ricoverati_con_sintomi",
                  "terapia_intensiva",
                  "totale_ospedalizzati",
                  "isolamento_domiciliare",
                  "totale_positivi",
                  "variazione_totale_positivi",
                  "nuovi_positivi",
                  "dimessi_guariti",
                  "deceduti",
                  "totale_casi",
                  "tamponi",
                  "casi_testati",
                  "ingressi_terapia_intensiva",
                  "totale_positivi_test_molecolare",
                  "totale_positivi_test_antigenico_rapido",
                  "tamponi_test_molecolare",
                  "tamponi_test_antigenico_rapido"
                ]
              }
            }
          },
          {
            "name": "mese",
            "in": "query",
            "description": "Mese da ricercare. Va riportato in formato <b>yyyy-mm</b>, ad esempio 2020-09 per ottenere i dati del mese di settembre 2020.<br> Questo parametro è incompatibile con `giorni`, `dataInizio`, `dataFine`",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "giorni",
            "in": "query",
            "description": "In base al valore N inserito, ritorna i record degli ultimi N giorni. Ad esempio, se il valore inserito è 30 ritorna i record degli ultimi 30 giorni. <br> Questo parametro è incompatibile con `mese`, `dataInizio`, `dataFine`.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "dataInizio",
            "in": "query",
            "description": "Data in formato <b>yyyy-mm-gg</b>. Vengono ritornati tutti i documenti con le date maggiori e uguali alla data specificata.<br> Questo parametro è incompatibile con `giorni`, `mese`.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "dataFine",
            "in": "query",
            "description": "Data in formato <b>yyyy-mm-gg</b>. Vengono ritornati tutti i documenti con le date minori e uguali alla data specificata.<br> Questo parametro è incompatibile con `giorni`, `mese`.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "summary": "Ritorna i dati riguardanti l'epidemia in una regione specifica.",
        "responses": {
          "200": {
            "description": "Risposta con un array di oggetti, ognuno rappresentante un giorno in una regione",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Regione"
                },
                "example": {
                  "data": "2021-03-27T17:00:00",
                  "stato": "ITA",
                  "codice_regione": 1,
                  "denominazione_regione": "Piemonte",
                  "lat": 45.0732745,
                  "long": 7.680687483,
                  "ricoverati_con_sintomi": 3767,
                  "terapia_intensiva": 360,
                  "totale_ospedalizzati": 4127,
                  "isolamento_domiciliare": 31458,
                  "totale_positivi": 35585,
                  "variazione_totale_positivi": 450,
                  "nuovi_positivi": 2636,
                  "dimessi_guariti": 256309,
                  "deceduti": 10180,
                  "casi_da_sospetto_diagnostico": null,
                  "casi_da_screening": null,
                  "totale_casi": 302074,
                  "tamponi": 3231331,
                  "casi_testati": 1484100,
                  "note": null,
                  "ingressi_terapia_intensiva": 27,
                  "note_test": null,
                  "note_casi": null,
                  "totale_positivi_test_molecolare": 288766,
                  "totale_positivi_test_antigenico_rapido": 13308,
                  "tamponi_test_molecolare": 2350377,
                  "tamponi_test_antigenico_rapido": 880954,
                  "codice_nuts_1": "ITC",
                  "codice_nuts_2": "ITC1"
                }
              }
            }
          }
        }
      }
    },
    "/nazione/": {
      "get": {
        "tags": [
          "Nazione"
        ],
        "description": "Ritorna tutti i dati riguardanti l'epidemia nella nazione raggruppati per giorno.\n",
        "operationId": "NazionefindAll",
        "parameters": [
          {
            "name": "campo",
            "in": "query",
            "description": "Campo specifico da ritornare. I campi <b>data</b>, <b>stato</b>, <b>codice_regione</b> e <b>denominazione_regione</b> sono ritornati in ogni caso.",
            "required": false,
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "ricoverati_con_sintomi",
                  "terapia_intensiva",
                  "totale_ospedalizzati",
                  "isolamento_domiciliare",
                  "totale_positivi",
                  "variazione_totale_positivi",
                  "nuovi_positivi",
                  "dimessi_guariti",
                  "deceduti",
                  "totale_casi",
                  "tamponi",
                  "casi_testati",
                  "ingressi_terapia_intensiva",
                  "totale_positivi_test_molecolare",
                  "totale_positivi_test_antigenico_rapido",
                  "tamponi_test_molecolare",
                  "tamponi_test_antigenico_rapido"
                ]
              }
            }
          },
          {
            "name": "mese",
            "in": "query",
            "description": "Mese da ricercare. Va riportato in formato <b>yyyy-mm</b>, ad esempio 2020-09 per ottenere i dati del mese di settembre 2020.<br> Questo parametro è incompatibile con `giorni`, `dataInizio`, `dataFine`",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "giorni",
            "in": "query",
            "description": "In base al valore N inserito, ritorna i record degli ultimi N giorni. Ad esempio, se il valore inserito è 30 ritorna i record degli ultimi 30 giorni. <br> Questo parametro è incompatibile con `mese`, `dataInizio`, `dataFine`.",
            "required": false,
            "schema": {
              "type": "integer"
            }
          },
          {
            "name": "dataInizio",
            "in": "query",
            "description": "Data in formato <b>yyyy-mm-gg</b>. Vengono ritornati tutti i documenti con le date maggiori e uguali alla data specificata.<br> Questo parametro è incompatibile con `giorni`, `mese`.",
            "required": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "dataFine",
            "in": "query",
            "description": "Data in formato <b>yyyy-mm-gg</b>. Vengono ritornati tutti i documenti con le date minori e uguali alla data specificata.<br> Questo parametro è incompatibile con `giorni`, `mese`.",
            "required": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "summary": "Ritorna tutti i dati riguardanti l'epidemia nella nazione raggruppati per giorno.",
        "responses": {
          "200": {
            "description": "Risposta con un array di oggetti, ognuno rappresentante un giorno nella nazione",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Nazione"
                },
                "example": {
                  "data": "2021-03-28T17:00:00",
                  "stato": "ITA",
                  "ricoverati_con_sintomi": 28701,
                  "terapia_intensiva": 3679,
                  "totale_ospedalizzati": 32380,
                  "isolamento_domiciliare": 540855,
                  "totale_positivi": 573235,
                  "variazione_totale_positivi": 1357,
                  "nuovi_positivi": 19611,
                  "dimessi_guariti": 2850889,
                  "deceduti": 107933,
                  "casi_da_sospetto_diagnostico": null,
                  "casi_da_screening": null,
                  "totale_casi": 3532057,
                  "tamponi": 49093293,
                  "casi_testati": 22718748,
                  "note": null,
                  "ingressi_terapia_intensiva": 217,
                  "note_test": null,
                  "note_casi": null,
                  "totale_positivi_test_molecolare": 3424211,
                  "totale_positivi_test_antigenico_rapido": 107846,
                  "tamponi_test_molecolare": 39824085,
                  "tamponi_test_antigenico_rapido": 9269208
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Regione": {
        "type": "object",
        "properties": {
          "data": {
            "type": "string"
          },
          "stato": {
            "type": "string"
          },
          "codice_regione": {
            "type": "integer"
          },
          "denominazione_regione": {
            "type": "string"
          },
          "lat": {
            "type": "number",
            "format": "double"
          },
          "long": {
            "type": "number",
            "format": "double"
          },
          "ricoverati_con_sintomi": {
            "type": "integer"
          },
          "terapia_intensiva": {
            "type": "integer"
          },
          "totale_ospedalizzati": {
            "type": "integer"
          },
          "isolamento_domiciliare": {
            "type": "integer"
          },
          "totale_positivi": {
            "type": "integer"
          },
          "variazione_totale_positivi": {
            "type": "integer"
          },
          "nuovi_positivi": {
            "type": "integer"
          },
          "dimessi_guariti": {
            "type": "integer"
          },
          "deceduti": {
            "type": "integer"
          },
          "casi_da_sospetto_diagnostico": {
            "type": "integer"
          },
          "casi_da_screening": {
            "type": "integer"
          },
          "totale_casi": {
            "type": "integer"
          },
          "tamponi": {
            "type": "integer"
          },
          "casi_testati": {
            "type": "integer"
          },
          "note": {
            "type": "string"
          },
          "ingressi_terapia_intensiva": {
            "type": "integer"
          },
          "note_test": {
            "type": "string"
          },
          "note_casi": {
            "type": "string"
          },
          "totale_positivi_test_molecolare": {
            "type": "integer"
          },
          "totale_positivi_test_antigenico_rapido": {
            "type": "integer"
          },
          "tamponi_test_molecolare": {
            "type": "integer"
          },
          "tamponi_test_antigenico_rapido": {
            "type": "integer"
          },
          "codice_nuts_1": {
            "type": "string"
          },
          "codice_nuts_2": {
            "type": "string"
          }
        }
      },
      "Nazione": {
        "type": "object",
        "properties": {
          "data": {
            "type": "string"
          },
          "stato": {
            "type": "string"
          },
          "ricoverati_con_sintomi": {
            "type": "integer"
          },
          "terapia_intensiva": {
            "type": "integer"
          },
          "totale_ospedalizzati": {
            "type": "integer"
          },
          "isolamento_domiciliare": {
            "type": "integer"
          },
          "totale_positivi": {
            "type": "integer"
          },
          "variazione_totale_positivi": {
            "type": "integer"
          },
          "nuovi_positivi": {
            "type": "integer"
          },
          "dimessi_guariti": {
            "type": "integer"
          },
          "deceduti": {
            "type": "integer"
          },
          "casi_da_sospetto_diagnostico": {
            "type": "integer"
          },
          "casi_da_screening": {
            "type": "integer"
          },
          "totale_casi": {
            "type": "integer"
          },
          "tamponi": {
            "type": "integer"
          },
          "casi_testati": {
            "type": "integer"
          },
          "note": {
            "type": "string"
          },
          "ingressi_terapia_intensiva": {
            "type": "integer"
          },
          "note_test": {
            "type": "string"
          },
          "note_casi": {
            "type": "string"
          },
          "totale_positivi_test_molecolare": {
            "type": "integer"
          },
          "totale_positivi_test_antigenico_rapido": {
            "type": "integer"
          },
          "tamponi_test_molecolare": {
            "type": "integer"
          },
          "tamponi_test_antigenico_rapido": {
            "type": "integer"
          },
          "__v": {
            "type": "integer"
          }
        }
      },
      "Error": {
        "type": "object",
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          }
        }
      }
    }
  }
}